### ISSUE TITLE
In Safari on MacOS `ESC` exists full screen mode

### ISSUE THREAD

**Issue by scharf** [oTranscribe/oTranscribe#42] opened 2015-05-06 19:15 UTC
`ESC` [exits fullscreen](https://support.apple.com/kb/PH17148?locale=en_US) mode in Safari. There should be a alternative shortcut to start/stop the video in safari.

**Comment by scharf** [comment] 2015-05-06 19:18
ESC is also the shortcut in [safari 8](http://help.apple.com/safari/mac/8.0/#/cpsh003)

**Comment by ejb** [comment] 2015-11-02 18:52
Hey, I realise that I'm very late to this issue but... I don't see this issue in version 9. Even though [Apple says Esc still exists fullscreen mode](https://support.apple.com/kb/PH21483?locale=en_US).

**Comment by npentrel** [comment] 2016-10-24 19:45
Can't reproduce.

**Comment by ejb** [comment] 2017-04-29 21:04
I just checked this on the latest version of Safari and it doesn't appear to be an issue. Closing.

**Closed by ejb** 2017-04-29 21:04 UTC
Labels: bug
